// Isolated PostgreSQL/WASM behavioral checks. Install @electric-sql/pglite in
// a temporary directory; pass its absolute dist/index.js path as argv[2].
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const { PGlite } = await import(process.argv[2]);
const db = new PGlite();
await db.exec(`
CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
CREATE SCHEMA auth;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql AS $$ SELECT current_setting('request.jwt.claim.role',true) $$;
CREATE TABLE auth.users(id uuid PRIMARY KEY,raw_user_meta_data jsonb DEFAULT '{}',email_confirmed_at timestamptz,phone_confirmed_at timestamptz);
CREATE TABLE public.platform_settings(key text PRIMARY KEY,value jsonb);
CREATE TABLE public.system_config(config_key text PRIMARY KEY,config_value text);
CREATE TABLE public.notifications(id uuid DEFAULT gen_random_uuid(),user_id uuid,type text,title text,message text);
CREATE TABLE public.wallets(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid UNIQUE,balance numeric DEFAULT 0,total_earned numeric DEFAULT 0,updated_at timestamptz);
CREATE TABLE public.wallet_transactions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),wallet_id uuid,type text,amount numeric,description text,idempotency_key text,cycle_id uuid,commission_id uuid,stripe_event_id text,status text);
CREATE TABLE public.revenue_entries(gross_amount numeric,net_eligible_amount numeric,year_month text,status text,is_pool_eligible boolean);
`);
const legacy = await readFile('supabase/migrations/20251123210401_bf1e1224-bad8-4b39-89d0-3e3fb13a1371.sql','utf8');
await db.exec(legacy.slice(0,legacy.indexOf('-- Enable RLS')));
const wallet = await readFile('supabase/migrations/20260910180100_economia_classfy_v1_foundation.sql','utf8');
const start = wallet.indexOf('CREATE OR REPLACE FUNCTION public.increment_wallet(');
await db.exec(wallet.slice(start,wallet.indexOf('TO service_role;',start)+16));
await db.exec(await readFile('supabase/migrations/20260928160000_harden_referral_attribution.sql','utf8'));
await db.exec(await readFile('supabase/migrations/20260928160100_referral_paid_purchase_reversals.sql','utf8'));
await db.exec(await readFile('supabase/migrations/20260928160200_referral_claim_cleanup_fk.sql','utf8'));
const referrer = '00000000-0000-4000-8000-000000000001';
const referred = '00000000-0000-4000-8000-000000000002';
await db.query('INSERT INTO auth.users(id,email_confirmed_at) VALUES($1,now())',[referrer]);
await db.query(`SELECT set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claim.role','authenticated',false)`,[referrer]);
const code = (await db.query('SELECT get_or_create_referral_link($1) code',[referrer])).rows[0].code;
await assert.rejects(db.query('SELECT get_or_create_referral_link($1)',[referred]),/not_authorized/);
assert.equal((await db.query("SELECT has_function_privilege('anon','public.get_or_create_referral_link(uuid)','EXECUTE') allowed")).rows[0].allowed,false);
assert.equal((await db.query("SELECT has_table_privilege('authenticated','public.referral_links','UPDATE') allowed")).rows[0].allowed,false);
await db.query(`SELECT set_config('request.jwt.claim.role','service_role',false)`);
for(let i=0;i<8;i++) await db.query('SELECT track_referral_click_v1($1,$2)',[code,'a'.repeat(64)]);
assert.equal((await db.query('SELECT total_clicks FROM referral_links')).rows[0].total_clicks,5);
await db.query('INSERT INTO auth.users(id,raw_user_meta_data) VALUES($1,$2)',[referred,JSON.stringify({referral_code:code,referral_expires:Date.now()+86400000})]);
assert.equal((await db.query('SELECT count(*)::int n FROM referral_conversions')).rows[0].n,0);
// Editable metadata cannot replace the captured signup attribution.
await db.query(`UPDATE auth.users SET raw_user_meta_data='{}',email_confirmed_at=now() WHERE id=$1`,[referred]);
await db.query('SELECT finalize_referral_signup_v1($1)',[referred]);
assert.equal((await db.query('SELECT total_conversions FROM referral_links')).rows[0].total_conversions,1);
assert.equal((await db.query('SELECT finalize_referral_signup_v1($1) result',[referrer])).rows[0].result.status,'no_claim');
const conversion = (await db.query('SELECT id FROM referral_conversions')).rows[0].id;
await db.query('SELECT process_referral_commission_v1($1,100,$2,$3)',[conversion,'subscription','pi_test']);
await db.query('SELECT process_referral_commission_v1($1,100,$2,$3)',[conversion,'subscription','pi_test']);
assert.equal(Number((await db.query('SELECT balance FROM wallets')).rows[0].balance),10);
await db.query("SELECT reverse_referral_commission_v1('pi_test','refund',30,'evt_1')");
await db.query("SELECT reverse_referral_commission_v1('pi_test','refund',30,'evt_duplicate')");
assert.equal(Number((await db.query('SELECT balance FROM wallets')).rows[0].balance),7);
await db.query("SELECT reverse_referral_commission_v1('pi_test','refund',100,'evt_2')");
assert.equal(Number((await db.query('SELECT balance FROM wallets')).rows[0].balance),0);
const another='00000000-0000-4000-8000-000000000003';
await db.query('INSERT INTO platform_settings VALUES($1,$2)', ['economic_v1','{"referral_commission_percent":0}']);
await db.query('INSERT INTO auth.users(id,raw_user_meta_data,email_confirmed_at) VALUES($1,$2,now())',[another,JSON.stringify({referral_code:code,referral_expires:Date.now()+86400000})]);
const zero = (await db.query('SELECT id FROM referral_conversions WHERE referred_user_id=$1',[another])).rows[0].id;
assert.equal((await db.query("SELECT process_referral_commission_v1($1,100,'payment','pi_zero') result",[zero])).rows[0].result.commission_amount,0);
await db.query('DELETE FROM auth.users WHERE id=$1',[referrer]);
assert.equal((await db.query('SELECT count(*)::int n FROM referral_signup_claims')).rows[0].n,0);
console.log('PASS: permissions, click cap, signup confirmation, immutable attribution, conversion/commission idempotency, partial/full refunds, zero rate.');
await db.close();
